version: '3'
services:
  flask_api:
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/api
    depends_on:
    - db
  db:
    restart: always
    image: postgres:15.4-bookworm
    volumes:
      - ./db:/usr/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
networks:
  webnet: